// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoZ.Persistence;

#nullable disable

namespace ProjetoZ.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260819043932_AddClasUnificado")]
    partial class AddClasUnificado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetoZ.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorys");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.Cla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estandarte")
                        .HasColumnType("text");

                    b.Property<string>("GrupoModId")
                        .HasColumnType("text");

                    b.Property<string>("LiderSteamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LiderUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GrupoModId")
                        .IsUnique()
                        .HasFilter("\"GrupoModId\" IS NOT NULL");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Clas");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.ClaMembro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EntrouEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClaId");

                    b.HasIndex("SteamId")
                        .IsUnique();

                    b.ToTable("ClaMembros");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.ClaSolicitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ClaId", "UserId")
                        .IsUnique();

                    b.ToTable("ClaSolicitacoes");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.Clipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Clipes");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.ClipeConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("UltimoFechamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UltimoVencedorAutorAvatar")
                        .HasColumnType("text");

                    b.Property<string>("UltimoVencedorAutorNome")
                        .HasColumnType("text");

                    b.Property<int?>("UltimoVencedorCurtidas")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoVencedorFechadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UltimoVencedorTitulo")
                        .HasColumnType("text");

                    b.Property<string>("UltimoVencedorUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClipeConfigs");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.ClipeCurtida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ClipeCurtidas");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.Compra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ValorReais")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriadoPorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnviarEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("ParaTodos")
                        .HasColumnType("boolean");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("EnviarEm");

                    b.HasIndex("ExpiraEm");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.NotificacaoDestinatario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotificacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("NotificacaoId", "UserId")
                        .IsUnique();

                    b.ToTable("NotificacaoDestinatarios");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.NotificacaoLeitura", b =>
                {
                    b.Property<Guid>("NotificacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NotificacaoId", "UserId");

                    b.ToTable("NotificacaoLeituras");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.PedidoCoins", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MercadoPagoPaymentId")
                        .HasColumnType("text");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PedidosCoins");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.PlayerRanking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int>("KothCompletados")
                        .HasColumnType("integer");

                    b.Property<int>("SegundosJogados")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ZumbiKills")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PlayerRankings");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Categoria")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estoque")
                        .HasColumnType("integer");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.Seguro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CarroId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("PosicaoAtualizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PosicaoGrid")
                        .HasColumnType("text");

                    b.Property<double?>("PosicaoX")
                        .HasColumnType("double precision");

                    b.Property<double?>("PosicaoZ")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UltimoResgate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VeiculoNome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarroId");

                    b.HasIndex("UserId");

                    b.ToTable("Seguros");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.Sorteio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("PremioProdutoIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int?>("PremioVipNivel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SorteadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VencedorUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Sorteios");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.SorteioParticipante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SorteioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SorteioParticipantes");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Banido")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BanidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BanidoMotivo")
                        .HasColumnType("text");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<Guid>>("Inventario")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VipExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VipNivel")
                        .HasColumnType("integer");

                    b.Property<string>("YoutubeChannelId")
                        .HasColumnType("text");

                    b.Property<string>("YoutubeChannelNome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("YoutubeChannelId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjetoZ.Domain.Entities.User", b =>
                {
                    b.OwnsOne("ProjetoZ.Domian.Models.SteamProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Avatar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ProfileUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SteamId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.HasIndex("SteamId")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
