<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>fdcf0bd3-7b88-4bed-a7a1-0edc7721a236</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNet.Security.OpenId.Steam" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjetoZ.Application\ProjetoZ.Application.csproj" />
    <ProjectReference Include="..\ProjetoZ.Domain\ProjetoZ.Domain.csproj" />
    <ProjectReference Include="..\ProjetoZ.Infrastructure\ProjetoZ.Infrastructure.csproj" />
    <ProjectReference Include="..\ProjetoZ.Persistence\ProjetoZ.Persistence.csproj" />
  </ItemGroup>

</Project>
